baseURL = 'https://hyaline.systems/'
languageCode = 'en-us'
title = 'hyaline.systems'
theme = "hyaline-theme"

pygmentsCodefences = true
pygmentsStyle = "nord"


[params.social]
# instagram = "https://instagram.com/madskjeld"
mastodon = "https://mastodon.social/@hyalinesystems"
# bandcamp = "https://mads-kjeldgaard.bandcamp.com/"
github = "https://github.com/hyaline-systems"

[outputs]
home = ["html", "rss"]

# Site parameters
[params]

siteSourceCode = "https://github.com/madskjeldgaard/hyaline.systems-public"

# Sub title
subtitle = ''

# Description
description = ''

# Menu
[[menu.main]]
identifier = "hyaline.systems"
name       = "⊂(◉‿◉)つ"
url        = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name       = "blog"
url        = "/blog"
weight = 2


# Minify all output
[minify]
minifyOutput = true
