baseURL = 'https://hyaline.systems/'
languageCode = 'en-us'
title = 'hyaline.systems'
theme = ["hugo-video","hyaline-theme", "hugo-audio", "hugo-email-shop"]

pygmentsCodefences = true
pygmentsStyle = "nord"
description = "A tiny creative technology studio based in Copenhagen, Denmark."


[params.social]
# instagram = "https://instagram.com/madskjeld"
mastodon = "https://mastodon.social/@hyalinesystems"
# bandcamp = "https://mads-kjeldgaard.bandcamp.com/"
github = "https://github.com/hyaline-systems"

[outputs]
home = ["html", "rss"]

# Site parameters
[params]

email = "hi@hyaline.systems"

siteSourceCode = "https://github.com/madskjeldgaard/hyaline.systems-public"

# Sub title
subtitle = ''

# Description
description = ''

purchaseInfo = "You can purchase our products by simply sending an email with the products you want to buy, the quantity and your shipping info, and we will get back to you with payment details :)"

purchaseEmail = "hi@hyaline.systems"

# Menu
[[menu.main]]
identifier = "hyaline.systems"
name       = "⊂(◉‿◉)つ"
url        = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name       = "blog"
url        = "/blog"
weight = 2

# Minify all output
[minify]
minifyOutput = true

disableHTML = false
disableCSS = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
disableMedia = true
