baseURL = 'https://hyaline.systems/'
languageCode = 'en-us'
title = 'hyaline.systems'
theme = "hyaline-theme"

[outputs]
home = ["html", "rss"]

# Site parameters
[params]

# Sub title
subtitle = ''

# Description
description = ''

# Menu
[[menu.main]]
identifier = "hyaline.systems"
name       = "⊂(◉‿◉)つ"
url        = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name       = "blog"
url        = "/blog"
weight = 2
